### ISSUE TITLE
Geofence.startListening is not working in android

### ISSUE THREAD

**Issue by adeelafzal** [DwayneCoussement/flutter_geofence#51]
Geofence.startListening is not working in android but working fine in IOS

**Comment by henriquetavolaro** [comment]
I'm having the same problem

**Comment by mvarendorff** [comment]
If you upgraded from an earlier version of the package, make sure to update AndroidManfest.xml with the correct package name in the receiver and service. It should look like this:

```xml
        <receiver android:name="com.intivoto.flutter_geofence.GeofenceBroadcastReceiver"
            android:enabled="true" android:exported="true"/>
        <service android:name="com.intivoto.flutter_geofence.FlutterGeofencePlugin"
            android:permission="android.permission.BIND_JOB_SERVICE" android:exported="true"/>
```

Older versions used `com.intivoto.geofence` as package name and `GeofencePlugin` (instead of `FlutterGeofencePlugin`). This appears to have been an undocumented breaking change in 0.4.1.
